
server:
  port: 9000


spring:
  application:
    name: spring-cloud-eureka
  profiles: test

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/