

server:
  port: 8000
spring:
  application:
    name: spring-cloud-eureka
  profiles: test

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
    register-with-eureka: false
    fetch-registry: false
---
#spring:
#  application:
#    name: spring-cloud-eureka
#  profiles: peer2
#server:
#  port: 8001
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8000/eureka/,http://localhost:8002/eureka/
#---
#spring:
#  application:
#    name: spring-cloud-eureka
#  profiles: peer3
#server:
#  port: 8002
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8000/eureka/,http://localhost:8001/eureka/
