spring:
  application:
    name: hystrix-dashboard-turbine
  profiles: test
server:
  port: 8001
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
turbine:
  combine-host-port: true
  app-config: node1,node2
  aggregator:
    cluster-config: default
  instanceUrlSuffix: /hystrix.stream
