spring:
  application:
    name: spring-cloud-consumer
  profiles: test
server:
  port: 9001
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

feign:
  hystrix:
    enabled: true
