spring:
  application:
    name: node1
  profiles: test
server:
  port: 9001
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
    register-with-eureka: true
feign:
  hystrix:
    enabled: true
