server:
  port: 8888


spring:
  application:
    name: gateway-service-zuul
#zuul:
#  routes:
#    api-a:
#      path: /producer/**
#      serviceId: spring-cloud-producer

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
zuul:
  retryable: true


ribbon:
  MaxAutoRetries: 2
  MaxAutoRetriesNextServer: 0
