spring:
  application:
    name: spring-cloud-producer
  profiles: test
server:
  port: 9000
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
