spring:
  zipkin:
    base-url: http://localhost:9000
    sleuth:
      sampler:
        percentage: 1.0
  application:
    name: spring-cloud-producer
server:
  port: 9001
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
